-- =============================================
-- Cheevo Database Seed Data
-- =============================================
-- Run this after running the main migration

-- =============================================
-- 1. SEED UNIVERSITIES
-- =============================================

-- Insert universities (with conflict resolution)
INSERT INTO public.universities (name, state) VALUES
    ('Michael Okpara University of Agriculture at Umudike', 'Abia'),
    ('Abia State University in Uturu', 'Abia'),
    ('College of Health Sciences Aba', 'Abia'),
    ('Abia State polytechnic', 'Abia'),
    ('Covenant Polytechnic, Aba', 'Abia'),
    ('Temple Gate Polytechnic, Abayi', 'Abia'),
    ('Valley View Polytechnic, Aba', 'Abia'),
    ('Gregory University Uturu', 'Abia'),
    ('Rhema University', 'Abia'),
    ('Adamawa State polytechnic, Yola', 'Adamawa'),
    ('Adamawa State University, Mubi', 'Adamawa'),
    ('Anambra State University, Anambra', 'Anambra'),
    ('Nnamdi Azikiwe University', 'Anambra'),
    ('the Federal Polytechnic, Oko', 'Anambra'),
    ('Nwafor Orizu University of Education', 'Anambra'),
    ('The Tansian University, Umunya', 'Anambra'),
    ('Madonna University, Okija', 'Anambra'),
    ('St Paul''s University, Awka', 'Anambra'),
    ('University of Uyo', 'Akwa Ibom'),
    ('Maritime Academy of Nigeria, Oron', 'Akwa Ibom'),
    ('Akwa Ibom State University [Oruk Anam LGA And Mkpat Enin LGA]', 'Akwa Ibom'),
    ('Obong University, Obong Ntak Inyang', 'Akwa Ibom'),
    ('Akwa Ibom State Polytechnic', 'Akwa Ibom'),
    ('Uyo City Polytechnic', 'Akwa Ibom'),
    ('Apex Polytechnic', 'Akwa Ibom'),
    ('Heritage Polytechnic, Eket', 'Akwa Ibom'),
    ('School of Nursing Uyo, Eket, Oron, Ikot Ekpene, Etinan', 'Akwa Ibom'),
    ('Akwa Ibom State College of Education, Afaha Nsit', 'Akwa Ibom'),
    ('School Of Basic Studies', 'Akwa Ibom'),
    ('College of Arts & Sciences, Nnung Ukim', 'Akwa Ibom'),
    ('Ritman University', 'Akwa Ibom'),
    ('Sure Polytechnic, Ukanafun', 'Akwa Ibom'),
    ('Abubakar Tafawa Balewa University', 'Bauchi'),
    ('Federal Polytechnic, Bauchi', 'Bauchi'),
    ('FGGC Bauchi', 'Bauchi'),
    ('Lys Children School', 'Bauchi'),
    ('College of Education - Azare', 'Bauchi'),
    ('National Open University Bauchi', 'Bauchi'),
    ('Bayelsa State College of Health Technology', 'Bayelsa'),
    ('Federal Polytechnic, Ekowe', 'Bayelsa'),
    ('Federal University, Otueke', 'Bayelsa'),
    ('Institute of Science and Technology Yenagoa', 'Bayelsa'),
    ('Niger Delta University', 'Bayelsa'),
    ('Federal Science and Technical College', 'Bayelsa'),
    ('Federal University of Agriculture, Makurdi', 'Benue'),
    ('Benue State University, Makurdi', 'Benue'),
    ('University of Mkar, Mkar, Gboko.', 'Benue'),
    ('Benue State Polytechnic, Ugbokolo', 'Benue'),
    ('Fidei polytechnic, Gboko', 'Benue'),
    ('Akperan Orshi college of Agriculture Yandev', 'Benue'),
    ('Federal College of Education Agasha', 'Benue'),
    ('College of Education Oju', 'Benue'),
    ('College of Education Kastina Ala.', 'Benue'),
    ('College of Education Waka-Biu', 'Borno'),
    ('Federal Training Centre, Maiduguri', 'Borno'),
    ('Federal University of Maiduguri', 'Borno'),
    ('MAI University Of Maiduguri, Maiduguri', 'Borno'),
    ('National Open University of Nigeria', 'Borno'),
    ('Ramat Polytechnic Maiduguri', 'Borno'),
    ('School of Health and Technology, Maiduguri', 'Borno'),
    ('School Of Nursing and Midwifery', 'Borno'),
    ('University of Calabar', 'Cross River'),
    ('Cross River State University of Technology, Calabar', 'Cross River'),
    ('Ibrahim Babangida College of Agriculture, Obubra', 'Cross River'),
    ('Cross River State College of Education, akamkpa', 'Cross River'),
    ('College of Health Technology, Iboko, Okpoma, Yala', 'Cross River'),
    ('Technical college Ugep', 'Cross River'),
    ('Federal University of Petroleum Resources, Effurun', 'Delta'),
    ('Delta State University', 'Delta'),
    ('Delta State Polytechnic, Ogwashi-Uku', 'Delta'),
    ('Delta State Polytechnic, Otefe-Oghara', 'Delta'),
    ('Delta State Polytechnic, Ozoro', 'Delta'),
    ('College of Education, Agbor', 'Delta'),
    ('College of Education, Warri', 'Delta'),
    ('Federal College of Education Technical, Asaba', 'Delta'),
    ('College of Physical Education, Mosogar', 'Delta'),
    ('School of Health Technology, Ughelli', 'Delta'),
    ('Petroleum Training Institute, Effurun', 'Delta'),
    ('Western Delta University, Oghara', 'Delta'),
    ('Novena University, Ogume-Amai', 'Delta'),
    ('National Open University of Nigeria, Asaba Study Center, Asaba', 'Delta'),
    ('Delta State School of Marine Technology, Burutu', 'Delta'),
    ('Nigerian Maritime University, Okerenkoko, Warri', 'Delta'),
    ('Conarina School of Maritime & Transport Technology, Oria-Abraka', 'Delta'),
    ('University of Information and Communication Technology, Agbor', 'Delta'),
    ('State School of Midwifery, Asaba', 'Delta'),
    ('School of Nursing, Agbor', 'Delta'),
    ('School of Nursing, Warri', 'Delta'),
    ('Baptist School of Nursing', 'Delta'),
    ('Eku Edwin Clark University', 'Delta'),
    ('Kiagbodo Eagle Heights University, Omadino', 'Delta'),
    ('Warri Nigerian Naval School', 'Delta'),
    ('Sapele Nigerian Navy Maritime University, Ibusa', 'Delta'),
    ('Ebonyi State University, Abakaliki', 'Ebonyi'),
    ('Federal University Ndufu Alike Ikwo', 'Ebonyi'),
    ('Ebonyi State College of Education Ikwo', 'Ebonyi'),
    ('Akanu Ibiam Federal Polytechnic, Unwana', 'Ebonyi'),
    ('College of Health Sciences', 'Ebonyi'),
    ('Ezzamgbo and Federal College of Agriculture, Ishiagu.', 'Ebonyi'),
    ('University of Nigeria, Nsukka', 'Enugu'),
    ('Enugu State University of Science & Technology', 'Enugu'),
    ('Institute of Management and Technology', 'Enugu'),
    ('Federal Cooperative College, Oji River', 'Enugu'),
    ('Enugu State College of Education Technical, Enugu', 'Enugu'),
    ('Caritas University, Amorji-Nike', 'Enugu'),
    ('Renaissance University, Ugbawka', 'Enugu'),
    ('Federal School of Dental Technology & Therapy', 'Enugu'),
    ('College of Immaculate Conception', 'Enugu'),
    ('Our Saviour Institute of Science and Technology, Enugu', 'Enugu'),
    ('the Federal College of Education', 'Enugu'),
    ('Eha-AmufuCaritas University', 'Enugu'),
    ('(ICE) Institute of Continuing Education, Auchi', 'Edo'),
    ('(MILI) Miracle Invasion Leadership Institute', 'Edo'),
    ('(NICPS) Nigerian Institute Of Computer Science And Professional Studies', 'Edo'),
    ('(SAU) Samuel Adegboyega University, Ogwa', 'Edo'),
    ('AAU Ambrose Ali University, Ekpoma', 'Edo'),
    ('BEN University Of Benin, Benin', 'Edo'),
    ('Bendel State University, Ekpoma', 'Edo'),
    ('Benin Technical College, Benin City', 'Edo'),
    ('BIU Benson Idahosa University, Benin City', 'Edo'),
    ('College of Education Benin', 'Edo'),
    ('Edo State Institute of Technology and Management Usen', 'Edo'),
    ('Federal Polytechnic Auchi', 'Edo'),
    ('IGB Igbinedion University, Okada-Benin', 'Edo'),
    ('Lighthouse Polytechnic, Evbuobanosa', 'Edo'),
    ('National Open University Of Nigeria', 'Edo'),
    ('Seminary of All Saints, Uhiele, Ekpoma', 'Edo'),
    ('Shaka Polytechnic, Benin City', 'Edo'),
    ('State School of Nursing, Sapele Road, Benin City', 'Edo'),
    ('Usen Polytechnic', 'Edo'),
    ('Wellspring University, Benin City', 'Edo'),
    ('World Outreach Bible College', 'Edo'),
    ('Afe Babalola University', 'Ekiti'),
    ('College of Education,Ikere-Ekiti', 'Ekiti'),
    ('Crown Polytechnic Ado Ekiti', 'Ekiti'),
    ('Divisional Teacher''s Training College, Oye-Ekiti', 'Ekiti'),
    ('Federal Polytechnic, Ado-Ekiti', 'Ekiti'),
    ('Federal University Oye Ekiti', 'Ekiti'),
    ('Government Technical College, Ado-Ekiti', 'Ekiti'),
    ('His Mercy Computer Institute', 'Ekiti'),
    ('School of Nursing', 'Ekiti'),
    ('UAD University Of Ado-Ekiti, Ado-Ekiti', 'Ekiti'),
    ('University Of Science And Technology, Ifaki', 'Ekiti'),
    ('(CABS) College of Administrative and Business Studies, Kumo', 'Gombe'),
    ('(FUK) Federal University Kashere', 'Gombe'),
    ('Federal College of Education (Tech) Gombe', 'Gombe'),
    ('GSU Gombe State University Tudun Wada, Tudun Wada', 'Gombe'),
    ('National Open University Of Nigeria', 'Gombe'),
    ('(CIP) Claretian Institute of Philosophy, Maryland Nekede', 'Imo'),
    ('African Institute Of Science And Technology', 'Imo'),
    ('ALV Alvan Ikoku College Of Education, Owerri', 'Imo'),
    ('College of Business and Legal Studies', 'Imo'),
    ('College of Health Science and Technology, Amaigbo, Nwangele', 'Imo'),
    ('Federal Polytechnic Nekede Owerri', 'Imo'),
    ('FUTO Fed University Of Technology, Owerri', 'Imo'),
    ('Imo State Polytechnic, Umuagwo', 'Imo'),
    ('Imo State Technological Skills Acquisition Institution, Orlu', 'Imo'),
    ('IMSU Imo State University, Owerri', 'Imo'),
    ('National Horticultural Research Institute, Ibadan', 'Imo'),
    ('National Open University of Nigeria', 'Imo'),
    ('School of Nursing', 'Imo'),
    ('Word of Faith Bible Institute', 'Imo'),
    ('Federal University, Dutse', 'Jigawa'),
    ('Hussaini Adamu Federal Polytechnic Kazaure', 'Jigawa'),
    ('informatics Institute of Information Technology, Kazaure', 'Jigawa'),
    ('Jigawa State College Of Agriculture, Hadejia', 'Jigawa'),
    ('Jigawa State College of Education, Gumel, Dutse', 'Jigawa'),
    ('Jigawa State Polytechnic', 'Jigawa'),
    ('(NTI) National Teacher''s Institute', 'Kaduna'),
    ('ABU Ahmadu Bello University, Zaria', 'Kaduna'),
    ('Air Force Institute Of Technology', 'Kaduna'),
    ('Ameer Shehu Idris College of Advanced Studies, Zaria', 'Kaduna'),
    ('Bouyeat Computer Training School', 'Kaduna'),
    ('Dialogue Computer Institute', 'Kaduna'),
    ('ECWA Theological Seminary Kagoro', 'Kaduna'),
    ('Fantsuam Foundation, Kafanchan', 'Kaduna'),
    ('Federal College of Chemical and Leather Technology', 'Kaduna'),
    ('Federal College Of Forestry Mechanization', 'Kaduna'),
    ('Federal Cooperative College', 'Kaduna'),
    ('Federal School of Statistics', 'Kaduna'),
    ('Federal Training Centre', 'Kaduna'),
    ('Gralom Computer Institute', 'Kaduna'),
    ('Innovation Institute of Technology', 'Kaduna'),
    ('KAD Kaduna Polytechnic, Kaduna', 'Kaduna'),
    ('Kaduna State College of Education', 'Kaduna'),
    ('KAS Kaduna State University, Kaduna', 'Kaduna'),
    ('National Open University of Nigeria, Kaduna', 'Kaduna'),
    ('Nigerian College Of Aviation Technology, Zaria', 'Kaduna'),
    ('Nigerian Defence Academy, Kaduna', 'Kaduna'),
    ('Nigerian Institute of Leather and Science Technology, Samuru', 'Kaduna'),
    ('Nuhu Bamalli Polytechnic Zaria', 'Kaduna'),
    ('School Of Health Technology, Makarfi', 'Kaduna'),
    ('St. Gerard''s School of Nursing, Kakuri', 'Kaduna'),
    ('St. Luke Anglican School of Nursing, Wusasa, Zaria', 'Kaduna'),
    ('The Federal College of Chemical and Leather Technology, Zaria', 'Kaduna'),
    ('ZAR Federal College Of Education, Zaria', 'Kaduna'),
    ('(SRCOE) Sa''adatu Rimi College Of Education, Kumbotso', 'Kano'),
    ('Aminu Kano College of Islamic And Legal Studies', 'Kano'),
    ('BAY Bayero University, Kano', 'Kano'),
    ('British Career Training College', 'Kano'),
    ('College of Art, Science and Remedial Studies', 'Kano'),
    ('Computer Training Institute', 'Kano'),
    ('Federal College of Education (Technical), Bichi', 'Kano'),
    ('KAN Federal College Of Education, Kano', 'Kano'),
    ('Kano State Polytechnic', 'Kano'),
    ('king''s Glory University', 'Kano'),
    ('KUT Kano University Of Technology, Kano', 'Kano'),
    ('Nigerian Police Academy, Wudil', 'Kano'),
    ('School of Health Technology', 'Kano'),
    ('Federal College of Education Katsina', 'Katsina'),
    ('Federal University Dutsin-Ma', 'Katsina'),
    ('Hassan Usman Katsina Polytechnic', 'Katsina'),
    ('Isah Kaita College of Education Dutsinma', 'Katsina'),
    ('KTS Katsina State University, Katsina', 'Katsina'),
    ('National Open University Of Nigeria', 'Katsina'),
    ('School of Basic and Remedial Studies Funtua', 'Katsina'),
    ('School of Health Technology Daura', 'Katsina'),
    ('School of Health Technology Kankia', 'Katsina'),
    ('School of Midwifery Malumfashi', 'Katsina'),
    ('School of Nursing Katsina', 'Katsina'),
    ('Umaru Musa Yaradua University', 'Katsina'),
    ('YBU College of Legal and General Studies Daura', 'Katsina'),
    ('Adamu Augie College of Education, Argungu', 'Kebbi'),
    ('KUS Kebbi State Univ. Of Science & Tech. Aliero, Aliero', 'Kebbi'),
    ('Waziri Umaru Federal Polytechnic', 'Kebbi'),
    ('ECWA School of Nursing', 'Kogi'),
    ('Federal College of Education, Okene', 'Kogi'),
    ('Federal University Of Lokoja', 'Kogi'),
    ('Kogi State College of Education', 'Kogi'),
    ('Kogi State College of Nursing', 'Kogi'),
    ('Kogi State Polytechnic, Lokoja', 'Kogi'),
    ('KSU Kogi State University, Anyigba', 'Kogi'),
    ('National Open University of Nigeria', 'Kogi'),
    ('SUL Salem University, Lokoja', 'Kogi'),
    ('The Federal Polytechnic Idah', 'Kogi'),
    ('College of Nursing, Ilorin', 'Kwara'),
    ('Federal Polytechnic Offa', 'Kwara'),
    ('HIK Al-Hikmah University, Ilorin', 'Kwara'),
    ('ILO University Of Ilorin, Ilorin', 'Kwara'),
    ('Kwara State College of Arabic and Islamic Legal Studies', 'Kwara'),
    ('Kwara State College of Education', 'Kwara'),
    ('Kwara State College of Health and Technology', 'Kwara'),
    ('Kwara State Polytechnic, Ilorin', 'Kwara'),
    ('Kwara State University', 'Kwara'),
    ('Landmark university omu-aran', 'Kwara'),
    ('National Open University of Nigeria', 'Kwara'),
    ('(CIBN) The Chartered Institute of Bankers of Nigeria', 'Lagos'),
    ('(CISN) Certified Institute of Shipping of Nigeria', 'Lagos'),
    ('(ICAN) The Institute of Chartered Accountants of Nigeria', 'Lagos'),
    ('(ISMN) Institute of Strategic Management, Nigeria', 'Lagos'),
    ('(LASOTAT) Lagos School of Travels and Tourism', 'Lagos'),
    ('(LBS) Lagos Business School', 'Lagos'),
    ('(NIPR) The Nigerian Institute Of Public Relations', 'Lagos'),
    ('(NITT) Nigerian Institute of Transport Technology', 'Lagos'),
    ('(NOIC) Nigerian Opportunity Industrialization Centre, Gbagada', 'Lagos'),
    ('Adeniran Ogunsanya College Of Education', 'Lagos'),
    ('Administrative Staff College of Nigeria (ASCON) Badagry', 'Lagos'),
    ('Aeroland Aviation School', 'Lagos'),
    ('African Maritime Academy', 'Lagos'),
    ('AMEC college', 'Lagos'),
    ('Aptech', 'Lagos'),
    ('Association of National Accountants of Nigeria', 'Lagos'),
    ('Bells Univ. Of Tech. Badagry, Badagry', 'Lagos'),
    ('Chartered Institute of Administration', 'Lagos'),
    ('Chartered Institute of Marketing of Nigeria', 'Lagos'),
    ('Chartered Institute of Purchasing and Supply Management', 'Lagos'),
    ('College Of Aviation And Management Studies', 'Lagos'),
    ('Command Day Secondary School, Ojo', 'Lagos'),
    ('Caleb University, Lagos', 'Lagos'),
    ('Dalewares Institute of Technology', 'Lagos'),
    ('Excel College', 'Lagos'),
    ('Ezekiel Private College', 'Lagos'),
    ('Federal College of Education', 'Lagos'),
    ('Federal College of Education (Technical), Akoka', 'Lagos'),
    ('Federal College of Fisheries and Marine Technology', 'Lagos'),
    ('Federal College Of Orthopedic Technology, Igbobi', 'Lagos'),
    ('Federal School of Arts and Sciences, Victoria Island', 'Lagos'),
    ('Federal School of Occupational Therapy', 'Lagos'),
    ('Federal School of Science', 'Lagos'),
    ('Federal Science and Technical College', 'Lagos'),
    ('Federal Training Centre, Ikoyi', 'Lagos'),
    ('First Immaculate Computer Institute', 'Lagos'),
    ('Goethe-Institut', 'Lagos'),
    ('Government Technical College, Ado-Soba', 'Lagos'),
    ('Government Technical College, Ikorodu', 'Lagos'),
    ('Grano Institute of Catering and Hotel Management', 'Lagos'),
    ('Helpers International College  Institute for Industrial Technology', 'Lagos'),
    ('Institute of Chartered Economists of Nigeria', 'Lagos'),
    ('Institute of Data Processing Management', 'Lagos'),
    ('Ipakodo Grammar School, Ikorodu', 'Lagos'),
    ('karROX ICT Institute', 'Lagos'),
    ('Keme Balogun College, Ibeshe', 'Lagos'),
    ('LAG University Of Lagos, Lagos', 'Lagos'),
    ('Lagos City Computer College', 'Lagos'),
    ('Lagos State College of Health Technology, Yaba', 'Lagos'),
    ('Lagos state polytechnic', 'Lagos'),
    ('Lagos University Teaching Hospital', 'Lagos'),
    ('LIFE Theological Seminary, Ikorodu,', 'Lagos'),
    ('Logos Institute, Maryland', 'Lagos'),
    ('LSU Lagos State University, Ojo Lagos', 'Lagos'),
    ('McAdolph Institute Of Information Technology', 'Lagos'),
    ('Michael Otedola College of Primary Education', 'Lagos'),
    ('National Open University of Nigeria', 'Lagos'),
    ('New Horizons Computer Learning Centres', 'Lagos'),
    ('Nigerian Army School Of Finance And Administration', 'Lagos'),
    ('Nigerian Army School Of Medical Sciences', 'Lagos'),
    ('Nigerian Army School of Nursing and Midwifery', 'Lagos'),
    ('Nigerian Institute of Journalism  Nigerian Institute Of Management', 'Lagos'),
    ('Nigerian Institute of Safety Professionals, Ikotun', 'Lagos'),
    ('Nigerian Law School', 'Lagos'),
    ('NIIT National Institute of Information Technology', 'Lagos'),
    ('PEFTI Film Institute  Portfolio And Debt Management Institute Of Nigeria', 'Lagos'),
    ('Redeemers University  Ronik Polytechnic', 'Lagos'),
    ('Saint Finbarr''s College, Akoka', 'Lagos'),
    ('Yaba  Speedway Information Technology Institute', 'Lagos'),
    ('Times Journalism Institute, Surulere', 'Lagos'),
    ('Wolex Polytechnic', 'Lagos'),
    ('YAB Yaba College Of Technology, Yaba, Lagos', 'Lagos'),
    ('Yetkem Institute of Catering and Hotel Management', 'Lagos'),
    ('Bingham University, Karu', 'Nasarawa'),
    ('BIN Gham University, New Karu', 'Nasarawa'),
    ('Federal University of Technology, Lafia', 'Nasarawa'),
    ('National Open University Of Nigeria', 'Nasarawa'),
    ('NSU Nasarawa State University, Keffi', 'Nasarawa'),
    ('College of Education, Akwanga', 'Nasarawa'),
    ('College of Agriculture, Lafia', 'Nasarawa'),
    ('FEDPOLYNAS Federal Polytechnic Nasarawa', 'Nasarawa'),
    ('Nacabs Polytechnic, Akwanga', 'Nasarawa'),
    ('Nasarawa State Polytechnic, Lafia', 'Nasarawa'),
    ('Federal University of Technology', 'Niger'),
    ('MIN Fed University Of Technology, Minna', 'Niger'),
    ('National Open University Of Nigeria', 'Niger'),
    ('Federal Polytechnic Bida', 'Niger'),
    ('Niger State Polytechnic, Zungeru', 'Niger'),
    ('(CABS) College of Administrative and Business Studies, Bida', 'Niger'),
    ('CEM College Of Education, Minna', 'Niger'),
    ('College for Legal and General Studies, Minna', 'Niger'),
    ('College of Arts and Islamic Legal Studies', 'Niger'),
    ('Federal College of Education, Kontagora', 'Niger'),
    ('Federal College of Wildlife Management, New Bussa', 'Niger'),
    ('Niger State College of Nursing, Bida', 'Niger'),
    ('Suleiman Barau Technical College, Suleja', 'Niger'),
    ('BAB Babcock University, Ilisan-Remo', 'Ogun'),
    ('Babcock University', 'Ogun'),
    ('Bells University of Technology', 'Ogun'),
    ('CRA Crawford University, Igbesa', 'Ogun'),
    ('Crescent University, Abeokuta', 'Ogun'),
    ('National Open University Of Nigeria', 'Ogun'),
    ('OOU Olabisi Onabanjo University, Ago-Iwoye', 'Ogun'),
    ('UAA University Of Agriculture, Abeokuta', 'Ogun'),
    ('Abraham Adesanya Polytechnic', 'Ogun'),
    ('Allover Central Polytechnic', 'Ogun'),
    ('D S Adegbenro Ict Polytechnic, Itoro, Ewekoro', 'Ogun'),
    ('Federal Polytechnic Ilaro', 'Ogun'),
    ('Grace Polytechnic', 'Ogun'),
    ('Moshood Abiola Polytechnic, Ojere, Abeokuta', 'Ogun'),
    ('The Gateway Polytechnic', 'Ogun'),
    ('Federal College of Education Abeokuta', 'Ogun'),
    ('Ifo College of Management and Technology', 'Ogun'),
    ('Ogun State College Of Health Technology', 'Ogun'),
    ('Savannah College of Art and Design', 'Ogun'),
    ('TAI Tai Solarin College Of Education, Ijebu-Ode', 'Ogun'),
    ('Yewa Central College of Education', 'Ogun'),
    ('Zulikha Abiola College of Arabic And Islamic Studies', 'Ogun'),
    ('Adekunle Ajasin University', 'Ondo'),
    ('Federal University of Technology, Akure', 'Ondo'),
    ('Rufus Giwa Polytechnic', 'Ondo'),
    ('Achievers University', 'Ondo'),
    ('University of Medical Sciences, Ondo', 'Ondo'),
    ('Ondo State University of Science and Technology', 'Ondo'),
    ('Wesley University of Science and Technology', 'Ondo'),
    ('Elizade University', 'Ondo'),
    ('Adeyemi College of Education, Ondo.', 'Ondo'),
    ('Adeleke University, Ede', 'Osun'),
    ('Bowen University, Iwo', 'Osun'),
    ('Christwealth University ifewara', 'Osun'),
    ('FUO Fountain University, Osogbo', 'Osun'),
    ('Ladoke Akintola University Of Technology Ogbomoso', 'Osun'),
    ('National Open University of Nigeria', 'Osun'),
    ('OAU Obafemi Awolowo University, Ile-Ife', 'Osun'),
    ('Obafemi Awolowo University Staff School, Ife', 'Osun'),
    ('Oduduwa University', 'Osun'),
    ('Osun State University, Osogbo', 'Osun'),
    ('University of Abu', 'Osun'),
    ('Federal Polytechnic Ede', 'Osun'),
    ('Interlink Polytechnic', 'Osun'),
    ('Osun State Polytechnic, Iree', 'Osun'),
    ('The Polytechnic, Ile-Ife', 'Osun'),
    ('Osun State College of Technolgy, Esa oke', 'Osun'),
    ('Universal College of Technology Ile-ife', 'Osun'),
    ('College of Arts and Science, Ile Ife', 'Osun'),
    ('OSC Osun State College Of Education Ilesa, Ilesa', 'Osun'),
    ('OSS college of EDucation, Ila-Orangun', 'Osun'),
    ('ACU Ajayi Crowther University, Oyo', 'Oyo'),
    ('University Of Ibadan, Ibadan', 'Oyo'),
    ('Lead City University, Ibadan', 'Oyo'),
    ('National Open University of Nigeria', 'Oyo'),
    ('The Polytechnic, Ibadan', 'Oyo'),
    ('St. Winifred Innovative Polytechnic, Ibadan', 'Oyo'),
    ('Tower Polytechnic, Ibadan', 'Oyo'),
    ('Best Legacy College of Education, Ogbomoso', 'Oyo'),
    ('Federal College of Agriculture, Moor Plantation, Ibadan', 'Oyo'),
    ('Federal College Of Animal Production and Health', 'Oyo'),
    ('Federal College of Education', 'Oyo'),
    ('Federal College of Forestry', 'Oyo'),
    ('Mufutau Lanihun College of Education, Ibadan', 'Oyo'),
    ('Oyo Stae College of Education', 'Oyo'),
    ('St. Andrews College Of Education, Oyo', 'Oyo'),
    ('JOS University Of Jos, Jos', 'Plateau'),
    ('PSU Plateau State University, Bokkos', 'Plateau'),
    ('Plateau State Polytechnic', 'Plateau'),
    ('(NCA) Nigerian College of Accountancy, Jos', 'Plateau'),
    ('College of Arabic and Islamic Studies(cais)Rikkos', 'Plateau'),
    ('College of Arts, Science and Technology, Kurgwi', 'Plateau'),
    ('College of Education, Jos', 'Plateau'),
    ('College of Health Technology, Zawan', 'Plateau'),
    ('Federal College of Education, Pankshin', 'Plateau'),
    ('Madonna University', 'Rivers'),
    ('National Open University Of Nigeria', 'Rivers'),
    ('University Of Port-Harcourt, Port-Harcourt', 'Rivers'),
    ('Rivers State University Of Technology, Port-Harcourt', 'Rivers'),
    ('University of Science and Technology, Diobu, Port Harcourt', 'Rivers'),
    ('Rivers State polytechnic', 'Rivers'),
    ('King''s College of Commerce, Buguma', 'Rivers'),
    ('Federal College of Education (Technical), Omoku', 'Rivers'),
    ('College Of Education, Port-Harcourt', 'Rivers'),
    ('Rivers State College Of Arts', 'Rivers'),
    ('Rivers State College of Health Science and Technology', 'Rivers'),
    ('Sokoto State University', 'Sokoto'),
    ('National Open University of Nigeria', 'Sokoto'),
    ('UDU Usmanu Danfodio University, Sokoto', 'Sokoto'),
    ('Usmanu Danfodiyo University Teaching Hospital School Of Nursing', 'Sokoto'),
    ('Sokoto State Polytechnic', 'Sokoto'),
    ('Haliru Binji College Of Art and Science', 'Sokoto'),
    ('Sokoto Teachers'' College', 'Sokoto'),
    ('TAR Taraba State University, Jalingo', 'Taraba'),
    ('Taraba State Polytechnic, Jalingo', 'Taraba'),
    ('Federal Science and Technical College', 'Taraba'),
    ('Taraba State College of Agriculture, Jalingo', 'Taraba'),
    ('Buka Abba Ibrahim University, Damaturu', 'Yobe'),
    ('Federal Polytechnic Damaturu', 'Yobe'),
    ('College of Administrative and Business Studies, Potiskum', 'Yobe'),
    ('College of Education, Gashua', 'Yobe'),
    ('Abdul Gusau Polytechnic', 'Zamfara'),
    ('Federal Polytechnic Kaura Namoda', 'Zamfara'),
    ('Kaura Knamoda Polytechnic', 'Zamfara'),
    ('College of Islamic Science, Gusau', 'Zamfara'),
    ('Federal University Gusau, Zamfara State', 'Zamfara'),
    ('(NTNU) Nigerian Turkish Nile University', 'Abuja'),
    ('African University of Science and Technology', 'Abuja'),
    ('National Open University of Nigeria', 'Abuja')
ON CONFLICT DO NOTHING;

-- =============================================
-- 2. SEED APP CONFIGURATION
-- =============================================

INSERT INTO public.app_config (key, value, category, description) VALUES
    -- Content & Engagement
    ('max_post_length', '280', 'content', 'Maximum characters allowed in a post'),
    ('max_comment_length', '140', 'content', 'Maximum characters allowed in a comment'),
    ('max_comments_per_post', '100', 'content', 'Maximum comments allowed per post'),
    ('max_replies_per_comment', '10', 'content', 'Maximum replies per comment'),
    ('comment_thread_depth', '3', 'content', 'Maximum depth of comment threads'),
    ('enable_reactions', 'true', 'content', 'Enable fire reactions on posts'),
    ('enable_comments', 'true', 'content', 'Enable comments on posts'),
    ('enable_gifs', 'true', 'content', 'Enable Giphy GIF integration'),
    
    -- Rate Limiting
    ('posts_per_hour', '10', 'rate_limiting', 'Maximum posts per user per hour'),
    ('posts_per_day', '50', 'rate_limiting', 'Maximum posts per user per day'),
    ('comments_per_hour', '30', 'rate_limiting', 'Maximum comments per user per hour'),
    ('comments_per_day', '100', 'rate_limiting', 'Maximum comments per user per day'),
    ('reactions_per_hour', '100', 'rate_limiting', 'Maximum reactions per user per hour'),
    ('reports_per_day', '10', 'rate_limiting', 'Maximum reports per user per day'),
    
    -- Trending Algorithm
    ('trending_window_hours', '24', 'trending', 'Time window for trending calculations'),
    ('trending_refresh_minutes', '15', 'trending', 'How often to refresh trending posts'),
    ('trending_min_reactions', '5', 'trending', 'Minimum reactions needed to be trending'),
    ('trending_boost_factor', '1.5', 'trending', 'Boost factor for trending score'),
    ('trending_decay_rate', '0.8', 'trending', 'Time decay rate for trending algorithm'),
    
    -- Feed Settings
    ('campus_feed_limit', '50', 'feeds', 'Number of posts to load in campus feed'),
    ('national_feed_limit', '100', 'feeds', 'Number of posts to load in national feed'),
    ('enable_national_feed', 'true', 'feeds', 'Enable Nigeria-wide trending feed'),
    ('show_reaction_counts', 'true', 'feeds', 'Show reaction counts on posts'),
    ('show_comment_counts', 'true', 'feeds', 'Show comment counts on posts'),
    
    -- Shadow Ban System
    ('first_ban_days', '7', 'moderation', 'Duration of first shadow ban in days'),
    ('second_ban_days', '14', 'moderation', 'Duration of second shadow ban in days'),
    ('third_ban_days', '28', 'moderation', 'Duration of third shadow ban in days'),
    ('fourth_ban_days', '56', 'moderation', 'Duration of fourth shadow ban in days'),
    ('max_ban_days', '180', 'moderation', 'Maximum ban duration before permanent (6 months)'),
    ('ban_escalation_reset_days', '90', 'moderation', 'Days after which violation count resets'),
    
    -- Feature Flags
    ('maintenance_mode', 'false', 'features', 'Enable maintenance mode'),
    ('new_user_registrations', 'true', 'features', 'Allow new user registrations'),
    ('giphy_integration', 'true', 'features', 'Enable Giphy API integration'),
    ('enable_reporting', 'true', 'features', 'Enable user reporting system'),
    ('enable_trending', 'true', 'features', 'Enable trending algorithm'),
    ('show_university_in_posts', 'true', 'features', 'Show university name in posts'),
    
    -- User Experience
    ('onboarding_required', 'true', 'user_experience', 'Require onboarding flow for new users'),
    ('username_min_length', '3', 'user_experience', 'Minimum username length'),
    ('username_max_length', '20', 'user_experience', 'Maximum username length'),
    ('force_app_update_version', 'null', 'user_experience', 'Force app update to this version')
ON CONFLICT (key) DO UPDATE SET
    value = EXCLUDED.value,
    updated_at = NOW();

-- =============================================
-- 3. SEED MODERATION CONFIGURATION
-- =============================================

INSERT INTO public.moderation_config (category, threshold, auto_action, applies_to) VALUES
    ('harassment', 0.70, 'manual_review', 'both'),
    ('harassment/threatening', 0.60, 'removed', 'both'),
    ('hate', 0.80, 'removed', 'both'),
    ('hate/threatening', 0.60, 'removed', 'both'),
    ('violence', 0.60, 'manual_review', 'both'),
    ('violence/graphic', 0.50, 'removed', 'both'),
    ('sexual', 0.80, 'removed', 'both'),
    ('sexual/minors', 0.30, 'removed', 'both'),
    ('self-harm', 0.50, 'manual_review', 'both'),
    ('self-harm/intent', 0.40, 'removed', 'both'),
    ('self-harm/instructions', 0.30, 'removed', 'both'),
    ('illicit', 0.70, 'manual_review', 'both'),
    ('illicit/violent', 0.50, 'removed', 'both')
ON CONFLICT (category, applies_to) DO UPDATE SET
    threshold = EXCLUDED.threshold,
    auto_action = EXCLUDED.auto_action,
    updated_at = NOW();

-- =============================================
-- SEED DATA COMPLETE
-- =============================================